name: MyFirstWorkflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: CheckoutRepo
          uses: actions/checkout@v4
        - name: Welcome message
          run : echo "welcome for first time"
         
        - name: list files
          run : ls

        - name: Read Files
          run : cat README.md
        - name: Install cowsay program
          run : cowsay -f dragon "Run for cover I am Dragon" >> dragon.txt

        - name: test exist file
          run: cat dragon.txt
