name: genrate-ascii 

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y

        - name: execute cowsay program
          run: cowsay -f dragon "Run for cover , i am dragon" >> dragon.txt

        - name: upload dragon txt file
          uses: actions/upload-artifact@v4
          with: 
            name:  Dragon text file
            path: dragon.txt 


    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon txt file
          uses: actions/download-artifact@v4
          with: 
              name: Dragon text file

        - name: test file if exist
          run: grep -i "dragon" dragon.txt

    deploy_job: 
        needs: test_job
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon txt file
          uses: actions/download-artifact@v4
          with: 
            name: Dragon text file
        
        - name: deploy
          run: echo deploying
        
